//PROBLEM 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let current;
let temp;
let past1;
let past2;

let sum = 2;
fibonacci(1,2,3);

function fibonacci(past1,past2,current){
  temp = current;
  current += past2;

  if(current % 2 == 0){
    sum += current;
    console.log('Sum of even numbers: ' +sum);//last one in output is the solution to the problem
  }

  if(sum < 4000000)
   fibonacci(past2,temp,current);
}


